### ISSUE TITLE
Plugin dont workin at 1.10.1 of NodeBB

### ISSUE THREAD

**Issue by necrosoul** [NicolasSiver/nodebb-plugin-ns-points#13]
Version - 1.10.1
base - mongodb
version of plugin - 4.0 and 5.0 

I inserted code with <import> at my theme (profile)

But at /points i see only one GUEST with 0 points.
I writed messages / new topics and i still not exist at /points and at my profile zero info about it.

What i need to do?

https://ibb.co/e6vUrK

this is my /points page.

**Comment by theportablegeek** [comment]
Receiving Error "Failed to load resource: the server responded with a status of 404 (Not Found)" when trying to view community.xxx.ca/api/user?_=1535151407119 on V1.10.1. Any Ideas?

**Comment by fais3000** [comment]
In our case, it is crashing nodebb. On version 1.10.2

`2018-12-01T08:33:11.010Z [4694] - [33mwarn[39m: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
[33m  * [39mnodebb-plugin-ns-points`

**Comment by K87N** [comment]
Can you please make it compatible with 1.12.x? 
I use this plugin a lot on my communities.

**Comment by kotritrona** [comment]
I somehow got it working in 1.12.0.

- Remove the 7th line (emitter: ...) in plugin\nodebb.js since it fails to load and is unused anyways.
- In plugin\actions.js, functions postSave and topicSave, change topicData.uid to postData.post.uid and topicData.topic.uid respectively.
- Register downvote hook/action. It only accounted for upvotes before (not sure if bug or feature)

I may make a pull request after cleaning up the mess here.
